### PR TITLE
Fixed bug with posts search

### PR DESCRIPTION
**Pull request by m-muhsin**
Results were not being restored after deleting search keyword. This is now fixed.

### CODE REVIEW

**Comment by m-muhsin** [comment]
Hi @ryelle could you add me as a Contributor so that we can fix this bug?

**Comment by ryelle** [comment]
Hi @m-muhsin — this project isn't really being worked on at the moment. I don't know if I'll pick it back up, and if I do I'd probably end up re-writing a lot of it based on what I learned with Foxhound.

However, if you want to fork it and work on your own version of Anadama, feel free to! And let me know what you create 😄

**Comment by m-muhsin** [comment]
Sure @ryelle. I already forked it and it was super useful for me 💯 
I used some parts of that project to build our Web Development Agency's site :) laccadive.io

Thanks for the awesome work you do and keep it up!!!

**Comment by cr101** [comment]
@m-muhsin It's an interesting way to build a React-powered WordPress theme, though under the hood it appears to be using jQuery more than React!

**Comment by m-muhsin** [comment]
@cr101 yes it is. A little bit of jQuery is used. The disadvantage is that it won't work on browsers which have disabled JavaScript.

**Comment by cr101** [comment]
@m-muhsin  

> The disadvantage is that it won't work on browsers which have disabled JavaScript.

Not sure how many people have JS disabled nowadays but perhaps you can display a message to the users who do.

**Comment by m-muhsin** [comment]
True that @cr101 . At the moment​ the loader will be rendered for browsers without JS.

**Pull request closed without merging**
